name: lint-and-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: './src'
        extensions: 'hpp,cpp,cu'

    - name: cmake build
      uses: lukka/run-cmake@v3.1
